import React, { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type User = { id: string; username: string; role: "admin" | "operator" | "viewer"; created_at?: string; disabled_at?: string | null };
type Instance = { id: string; node_id?: string; cluster_id?: string; map_name: string; desired_state: string; observed_state: string; health: string; last_error?: string | null; ports?: Record<string, number> };
type Job = { id: string; instance_id?: string | null; kind: string; status: string; last_error?: string | null; created_at: string };
type Audit = { id: number; actor: string; action: string; resource: string; metadata: Record<string, unknown>; created_at: string };
type Health = { status?: string; control_plane?: string; database?: string; agent?: string; ark?: string; observed_at?: string };
type Node = { id: string; name: string; endpoint: string; status: string; last_heartbeat?: string | null; created_at?: string | null };
type Backup = { id: string; instance_id: string; backend: string; object_key: string; sha256: string; bytes: number; verified_at?: string | null; created_by?: string | null; created_at: string };

const api = async <T,>(path: string, init?: RequestInit): Promise<T> => {
  const response = await fetch(`/api/v1${path}`, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(init?.headers || {}) }, ...init });
  if (response.status === 401 && path !== "/auth/login" && path !== "/auth/status") window.dispatchEvent(new Event("ark:session-expired"));
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body?.error?.message || "Request failed"); }
  if (response.status === 204) return undefined as T;
  return response.json();
};

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { const result = await api<{ user: User }>("/auth/login", { method: "POST", body: JSON.stringify({ username, password }) }); onLogin(result.user); } catch (e) { setError(e instanceof Error ? e.message : "Unable to sign in"); } finally { setBusy(false); } }
  return <main className="login-layout"><section className="login-visual"><div className="brand-mark">A<span>•</span></div><p className="eyebrow">ARK ASA / OPERATIONS</p><h1>Keep your<br /><em>world online.</em></h1><p className="login-copy">A calm command surface for servers, jobs, and the people who keep your cluster moving.</p><div className="orbit"><span /><span /><span /></div></section><section className="login-panel"><div className="login-card"><p className="eyebrow">SECURE ACCESS</p><h2>Welcome back</h2><p className="muted">Sign in to your operations console.</p><form onSubmit={submit}><label>Username<input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} placeholder="admin" required /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••••••" required /></label>{error && <div className="alert error" role="alert">{error}</div>}<button className="primary wide" disabled={busy}>{busy ? "Signing in…" : "Enter console"}<span>↗</span></button></form><p className="security-note">Sessions are protected with secure, same-origin cookies.</p></div></section></main>;
}

function App() {
  const [user, setUser] = useState<User | null>(null); const [checking, setChecking] = useState(true); const [page, setPage] = useState(() => pageFromPath(window.location.pathname)); const [nodeHealth, setNodeHealth] = useState("unknown");
  useEffect(() => {
    api<{ authenticated: boolean; user?: User }>("/auth/status").then(r => setUser(r.authenticated ? r.user || null : null)).catch(() => setUser(null)).finally(() => setChecking(false));
  }, []);
  useEffect(() => { const onPopState = () => setPage(pageFromPath(window.location.pathname)); window.addEventListener("popstate", onPopState); return () => window.removeEventListener("popstate", onPopState); }, []);
  useEffect(() => { const onExpired = () => { window.history.replaceState({}, "", "/login"); setPage("overview"); setUser(null); }; window.addEventListener("ark:session-expired", onExpired); return () => window.removeEventListener("ark:session-expired", onExpired); }, []);
  useEffect(() => { if (!checking && !user && window.location.pathname !== "/" && window.location.pathname !== "/login") { window.history.replaceState({}, "", "/login"); setPage("overview"); } }, [checking, user]);
  useEffect(() => { if (user && window.location.pathname === "/login") { window.history.replaceState({}, "", "/"); setPage("overview"); } }, [user]);
  useEffect(() => {
    if (!user) return;
    let stopped = false;
    const refresh = () => void api<any>("/system/health").then(r => { if (!stopped) setNodeHealth(r.agent || "unknown"); }).catch(() => { if (!stopped) setNodeHealth("unknown"); });
    refresh();
    const timer = window.setInterval(refresh, 10000);
    return () => { stopped = true; window.clearInterval(timer); };
  }, [user]);
  if (checking) return <div className="loading-screen"><div className="spinner" />Loading console</div>;
  if (!user) return <Login onLogin={next => { window.history.replaceState({}, "", "/"); setPage("overview"); setUser(next); }} />;
  async function logout() { await api("/auth/logout", { method: "POST", headers: { "X-CSRF-Token": await csrfToken() } }).catch(() => undefined); window.history.replaceState({}, "", "/login"); setPage("overview"); setUser(null); }
  function navigate(next: string) { window.history.pushState({}, "", next === "overview" ? "/" : `/${next}`); setPage(next); }
  return <div className="app-shell"><Sidebar page={page} setPage={navigate} user={user} logout={logout} nodeHealth={nodeHealth} /><main className="content"><header className="topbar"><div><p className="eyebrow">CONTROL PLANE / LOCAL</p><h1>{page === "overview" ? "Good evening, " + user.username : pageLabel(page)}</h1></div><div className="top-actions"><span className="live-pill"><i /> Live</span><div className="avatar">{user.username.slice(0, 1).toUpperCase()}</div></div></header>{page === "overview" && <Overview user={user} />}{page === "servers" && <Servers user={user} />}{page === "recovery" && <Recovery user={user} />}{page === "jobs" && <Jobs />}{page === "audit" && <Audit />}{page === "nodes" && (user.role === "admin" ? <Nodes /> : <ForbiddenPage />)}{page === "users" && (user.role === "admin" ? <Users currentUser={user} /> : <ForbiddenPage />)}</main></div>;
}

function Sidebar({ page, setPage, user, logout, nodeHealth }: { page: string; setPage: (p: string) => void; user: User; logout: () => void; nodeHealth: string }) { const links = [{ id: "overview", label: "Overview", icon: "⌂" }, { id: "servers", label: "Servers", icon: "◈" }, { id: "recovery", label: "Recovery", icon: "▣" }, { id: "jobs", label: "Jobs", icon: "◌" }, { id: "audit", label: "Audit trail", icon: "≡" }]; const label = nodeHealth === "healthy" ? "healthy" : nodeHealth === "degraded" ? "degraded" : "checking"; return <aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark small">A<span>•</span></div><span>ARK / OPS</span></div><nav aria-label="Primary navigation">{links.map(link => <button aria-current={page === link.id ? "page" : undefined} aria-label={link.label} title={link.label} className={page === link.id ? "nav-link active" : "nav-link"} key={link.id} onClick={() => setPage(link.id)}><b aria-hidden="true">{link.icon}</b>{link.label}</button>)}{user.role === "admin" && <><button aria-current={page === "nodes" ? "page" : undefined} aria-label="Nodes" title="Nodes" className={page === "nodes" ? "nav-link active" : "nav-link"} onClick={() => setPage("nodes")}><b aria-hidden="true">⌁</b>Nodes</button><button aria-current={page === "users" ? "page" : undefined} aria-label="Team access" title="Team access" className={page === "users" ? "nav-link active" : "nav-link"} onClick={() => setPage("users")}><b aria-hidden="true">♙</b>Team access</button></>}</nav><div className="sidebar-bottom"><div className="node-status"><i />Local node <span>{label}</span></div><button className="logout" onClick={logout} aria-label="Sign out" title="Sign out">↪ <span>Sign out</span></button></div></aside> }
function pageFromPath(path: string) { const page = path.replace(/^\//, ""); return ["servers", "recovery", "jobs", "audit", "nodes", "users"].includes(page) ? page : "overview"; }
function pageLabel(page: string) { return ({ servers: "Servers", recovery: "Recovery", jobs: "Jobs", audit: "Audit trail", nodes: "Nodes", users: "Team access" } as Record<string, string>)[page] || "Overview"; }
function getCookie(name: string) { return document.cookie.split("; ").find(v => v.startsWith(`${name}=`))?.slice(name.length + 1) || ""; }
async function csrfToken() { if (!getCookie("ark_csrf")) await api("/auth/csrf"); return getCookie("ark_csrf"); }
function Metric({ label, value, detail, tone = "green" }: { label: string; value: string; detail: string; tone?: string }) { return <article className="metric card"><div className={`metric-icon ${tone}`}>{tone === "green" ? "✓" : tone === "amber" ? "◌" : "⌁"}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article> }
function ForbiddenPage() { return <div className="empty card"><div className="empty-icon">⊘</div><h3>Access restricted</h3><p>Your role can view operations, but only administrators can manage team access.</p></div> }

function Overview({ user }: { user: User }) {
  const [health, setHealth] = useState<Health | null>(null); const [instances, setInstances] = useState<Instance[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [audit, setAudit] = useState<Audit[]>([]); const [error, setError] = useState("");
  useEffect(() => {
    const load = () => Promise.all([api<Health>("/system/health"), api<{ items: Instance[] }>("/instances?limit=50"), api<{ items: Job[] }>("/jobs?limit=5"), api<{ items: Audit[] }>("/audit?limit=5")]).then(([h, i, j, a]) => { setHealth(h); setInstances(i.items); setJobs(j.items); setAudit(a.items); }).catch(e => setError(e.message));
    void load();
    const scheme = window.location.protocol === "https:" ? "wss" : "ws"; let cursor = 0; let stopped = false; let retry: number | undefined; let fallback: number | undefined; let socket: WebSocket;
    const stopFallback = () => { if (fallback) { window.clearInterval(fallback); fallback = undefined; } };
    const startFallback = () => { if (!fallback) fallback = window.setInterval(() => void load(), 5000); };
    const connect = () => { if (stopped) return; socket = new WebSocket(`${scheme}://${window.location.host}/api/v1/ws?cursor=${cursor}`); socket.onopen = () => stopFallback(); socket.onmessage = event => { try { const message = JSON.parse(event.data); if (message?.type === "event") { cursor = Number(message.cursor) || cursor; void load(); } } catch { setError("Realtime event stream returned invalid data"); } }; socket.onerror = () => startFallback(); socket.onclose = () => { if (!stopped) { startFallback(); retry = window.setTimeout(connect, 2000); } }; };
    connect();
    return () => { stopped = true; stopFallback(); if (retry) window.clearTimeout(retry); socket?.close(); };
  }, []);
  const instance = instances[0]; const agentValue = health?.agent === "healthy" ? "Ready" : health?.agent === "degraded" ? "Degraded" : "Checking"; return <div className="page-stack">{error && <div className="alert error">{error}</div>}<section className="hero-grid"><div className="hero-card card"><div><p className="eyebrow amber">OPERATIONS AT A GLANCE</p><h2>Your servers,<br /><em>in good hands.</em></h2><p>Monitor health, trigger safe actions, and keep a clean record of every change.</p></div><div className="hero-ring"><span>{instances.length}</span><small>instances</small></div></div><div className="metric-grid"><Metric label="Control plane" value={health?.control_plane === "healthy" ? "Healthy" : "Checking"} detail="Database connected" /><Metric label="Agent node" value={agentValue} detail={health?.agent === "healthy" ? "Last heartbeat · live" : "Heartbeat unavailable"} tone="blue" /></div></section><section className="section-heading"><div><p className="eyebrow">YOUR INFRASTRUCTURE</p><h2>Server overview</h2></div><span className="subtle">{instances.length} instance{instances.length === 1 ? "" : "s"}</span></section>{instance ? <ServerCard instance={instance} user={user} /> : <div className="empty card"><div className="empty-icon">◈</div><h3>No server registered yet</h3><p>Once an instance is connected to the local node, it will appear here.</p></div>}<section className="section-heading compact"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Latest jobs</h2></div><span className="subtle">Last 5</span></section><JobTable jobs={jobs} /><section className="section-heading compact"><div><p className="eyebrow">ACCOUNTABILITY</p><h2>Recent audit</h2></div><span className="subtle">Last 5</span></section><AuditList items={audit} /></div>
}

function ServerCard({ instance, user, onDelete }: { instance: Instance; user?: User; onDelete?: (id: string) => void }) {
  const [busy, setBusy] = useState(""); const [feedback, setFeedback] = useState(""); const [feedbackError, setFeedbackError] = useState(false); const [editing, setEditing] = useState(false); const [mapName, setMapName] = useState(instance.map_name); const [clusterID, setClusterID] = useState(instance.cluster_id || ""); const [displayMapName, setDisplayMapName] = useState(instance.map_name); const [displayClusterID, setDisplayClusterID] = useState(instance.cluster_id || ""); const canOperate = user?.role !== "viewer";
  async function action(name: string) { if (!canOperate) return; if ((name === "stop" || name === "restart") && !window.confirm(`Confirm ${name} for ${instance.id}?`)) return; setFeedback(""); setFeedbackError(false); setBusy(name); try { await api(`/instances/${instance.id}/actions/${name}`, { method: "POST", headers: { "X-CSRF-Token": await csrfToken() } }); setFeedback(`${name[0].toUpperCase() + name.slice(1)} queued. Track progress in Jobs.`); } catch (e) { setFeedbackError(true); setFeedback(e instanceof Error ? e.message : "Could not queue action"); } finally { setBusy(""); } }
  async function saveSettings(event: FormEvent) { event.preventDefault(); if (!canOperate) return; const nextMap = mapName.trim(); const nextCluster = clusterID.trim(); setFeedback(""); setFeedbackError(false); setBusy("save"); try { await api(`/instances/${instance.id}`, { method: "PATCH", headers: { "X-CSRF-Token": await csrfToken() }, body: JSON.stringify({ map: nextMap, cluster_id: nextCluster }) }); setDisplayMapName(nextMap); setDisplayClusterID(nextCluster); setEditing(false); setFeedback("Server settings saved."); } catch (e) { setFeedbackError(true); setFeedback(e instanceof Error ? e.message : "Could not save server settings"); } finally { setBusy(""); } }
  const isRunning = instance.observed_state === "running";
  const isStopped = instance.observed_state === "stopped";
  return <article className="server-card card">
    <div className="server-title"><div className="server-icon">✦</div><div><h3>{instance.id}</h3><p>{displayMapName} · desired {instance.desired_state}</p></div><span className={`status ${instance.health === "healthy" ? "ok" : "warn"}`}><i />{instance.health}</span></div>
    <div className="server-meta"><div><span>OBSERVED STATE</span><strong>{instance.observed_state}</strong></div><div><span>CLUSTER</span><strong>{displayClusterID || "—"}</strong></div><div><span>NODE</span><strong>{instance.node_id || "—"}</strong></div></div>
    <div className="server-ports"><span>ALLOCATED PORTS</span><div>{Object.entries(instance.ports || {}).sort(([a], [b]) => a.localeCompare(b)).map(([purpose, port]) => <span className="port-chip" key={purpose}><b>{purpose}</b>{port}</span>)}</div></div>
    {instance.last_error && <div className="alert error server-error" role="alert">Last observed error: {instance.last_error}</div>}
    {editing && <form className="settings-form" onSubmit={saveSettings}><div><label htmlFor={`map-${instance.id}`}>Map<input id={`map-${instance.id}`} value={mapName} onChange={e => setMapName(e.target.value)} required /></label><label htmlFor={`cluster-${instance.id}`}>Cluster<input id={`cluster-${instance.id}`} value={clusterID} onChange={e => setClusterID(e.target.value)} required /></label></div><div className="settings-actions"><button type="button" onClick={() => setEditing(false)} disabled={!!busy}>Cancel</button><button className="primary" disabled={busy === "save"}>{busy === "save" ? "Saving…" : "Save settings"}</button></div></form>}
    <div className="server-actions"><button onClick={() => action("start")} disabled={!!busy || !canOperate || isRunning} title={isRunning ? "Server is already running" : !canOperate ? "Viewer access is read-only" : undefined}>Start</button><button onClick={() => action("restart")} disabled={!!busy || !canOperate} title={!canOperate ? "Viewer access is read-only" : undefined}>Restart</button><button className="danger" onClick={() => action("stop")} disabled={!!busy || !canOperate || isStopped} title={isStopped ? "Server is already stopped" : !canOperate ? "Viewer access is read-only" : undefined}>{busy === "stop" ? "Stopping…" : "Stop"}</button><button onClick={() => { setMapName(displayMapName); setClusterID(displayClusterID); setEditing(!editing); }} disabled={!!busy || !canOperate} title={!canOperate ? "Viewer access is read-only" : undefined}>{editing ? "Close" : "Edit settings"}</button>{onDelete && <button className="danger delete-action" onClick={() => onDelete(instance.id)} disabled={!!busy || !canOperate || !isStopped} title={!isStopped ? "Stop the server before deleting it" : undefined}>Delete</button>}</div>
    {feedback && <div className={`action-feedback ${feedbackError ? "error" : "success"}`} role="status" aria-live="polite">{feedback}</div>}
  </article>
}
function Servers({ user }: { user: User }) {
  const [items,setItems]=useState<Instance[]>([]); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [id,setID]=useState(""); const [nodeID,setNodeID]=useState("local-node"); const [map,setMap]=useState("TheIsland_WP"); const [clusterID,setClusterID]=useState("local-cluster"); const canOperate=user.role !== "viewer";
  const load=()=>api<{items:Instance[]}>("/instances").then(r=>{setItems(r.items);setError("")}).catch(e=>setError(e.message)); useEffect(()=>{let stopped=false; const refresh=()=>{if(!stopped) void load()}; refresh(); const timer=window.setInterval(refresh,5000); return()=>{stopped=true;window.clearInterval(timer)}},[]);
  async function create(event: FormEvent) { event.preventDefault(); if (!canOperate) return; setError(""); setNotice(""); setBusy(true); try { await api("/instances", { method:"POST", headers:{"X-CSRF-Token":await csrfToken()}, body:JSON.stringify({id:id.trim(),node_id:nodeID.trim(),map:map.trim(),cluster_id:clusterID.trim(),desired_state:"stopped"}) }); setNotice(`${id.trim()} registered and queued for reconciliation.`); setID(""); setOpen(false); await load(); } catch(e) { setError(e instanceof Error ? e.message : "Could not register server"); } finally { setBusy(false); } }
  async function remove(idToDelete: string) { if (!window.confirm(`Delete ${idToDelete}? The stopped container will be removed; persistent volumes are retained for recovery.`)) return; setError(""); setNotice(""); setBusy(true); try { await api(`/instances/${idToDelete}`, { method: "DELETE", headers: { "X-CSRF-Token": await csrfToken() } }); setNotice(`${idToDelete} deleted. Persistent volumes were retained.`); await load(); } catch(e) { setError(e instanceof Error ? e.message : "Could not delete server"); } finally { setBusy(false); } }
  return <div className="page-stack">{error && <div className="alert error" role="alert">{error}</div>}{notice && <div className="alert success" role="status">{notice}</div>}<section className="section-heading"><div><p className="eyebrow">INFRASTRUCTURE</p><h2>Servers</h2></div><div className="heading-actions"><span className="subtle">{user.role} access · auto-refresh 5s</span>{canOperate && <button className="primary" onClick={() => { setError(""); setNotice(""); setOpen(!open); }}>{open ? "Close form" : "+ Register server"}</button>}</div></section>{open && <form className="card invite-card" onSubmit={create}><p className="eyebrow">NEW ARK INSTANCE</p><div className="form-row server-form-row"><input aria-label="Instance ID" value={id} onChange={e=>setID(e.target.value)} placeholder="Instance ID" required /><input aria-label="Node ID" value={nodeID} onChange={e=>setNodeID(e.target.value)} placeholder="Node ID" required /><input aria-label="Map name" value={map} onChange={e=>setMap(e.target.value)} placeholder="Map name" required /><input aria-label="Cluster ID" value={clusterID} onChange={e=>setClusterID(e.target.value)} placeholder="Cluster ID" required /><button className="primary" disabled={busy}>{busy ? "Registering…" : "Register"}</button></div><p className="subtle form-help">The instance starts stopped. The local agent will reconcile it from its stable labels.</p></form>}{items.length ? items.map(i=><ServerCard key={i.id} instance={i} user={user} onDelete={remove}/>) : <div className="empty card"><div className="empty-icon">◈</div><h3>No servers found</h3><p>Register an instance with the control plane to start managing it.</p></div>}</div>
}
function Recovery({ user }: { user: User }) {
  const [backups, setBackups] = useState<Backup[]>([]); const [instances, setInstances] = useState<Instance[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(""); const canOperate = user.role !== "viewer";
  const load = () => Promise.all([api<{ items: Backup[] }>("/backups?limit=50"), api<{ items: Instance[] }>("/instances?limit=50")]).then(([b, i]) => { setBackups(b.items); setInstances(i.items); setError(""); }).catch(e => setError(e instanceof Error ? e.message : "Could not load recovery data"));
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 5000); return () => window.clearInterval(timer); }, []);
  async function queue(instanceID: string, action: "backup" | "restore", backupID?: string) { if (!canOperate) return; if (action === "restore" && !window.confirm(`Restore ${backupID} to ${instanceID}? The server must remain stopped.`)) return; setBusy(`${action}:${instanceID}`); setError(""); setNotice(""); try { await api(`/instances/${instanceID}/actions/${action}`, { method: "POST", headers: { "X-CSRF-Token": await csrfToken() }, body: JSON.stringify(backupID ? { backup_id: backupID } : {}) }); setNotice(`${action === "backup" ? "Backup" : "Restore"} queued for ${instanceID}. Track progress in Jobs.`); await load(); } catch (e) { setError(e instanceof Error ? e.message : `Could not queue ${action}`); } finally { setBusy(""); } }
  const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  return <div className="page-stack">{error && <div className="alert error" role="alert">{error}</div>}{notice && <div className="alert success" role="status">{notice}</div>}<section className="section-heading"><div><p className="eyebrow">DATA PROTECTION</p><h2>Recovery</h2><p className="subtle">Verified local save archives. Restore is available only while the server is stopped.</p></div><span className="subtle">Auto-refresh 5s</span></section><div className="recovery-grid">{instances.map(instance => <article className="card recovery-card" key={instance.id}><div><p className="eyebrow">SERVER</p><h3>{instance.id}</h3><p className="subtle">{instance.map_name} · observed {instance.observed_state}</p></div><button className="primary" disabled={!canOperate || !!busy || busy === `backup:${instance.id}`} onClick={() => void queue(instance.id, "backup")}>{busy === `backup:${instance.id}` ? "Creating…" : "Create backup"}</button></article>)}</div><div className="section-heading compact"><div><p className="eyebrow">ARCHIVE CATALOG</p><h2>Available backups</h2></div><span className="subtle">{backups.length} archive{backups.length === 1 ? "" : "s"}</span></div><div className="table-card card"><div className="table-head recovery-head"><span>ARCHIVE</span><span>SERVER</span><span>SIZE</span><span>CREATED</span><span>ACTION</span></div>{backups.length ? backups.map(backup => { const instance = instances.find(item => item.id === backup.instance_id); const stopped = instance?.observed_state === "stopped"; return <div className="table-row recovery-row" key={backup.id}><span className="mono" title={backup.sha256}>{backup.id}</span><span>{backup.instance_id}</span><span>{formatBytes(backup.bytes)}</span><span className="subtle">{new Date(backup.created_at).toLocaleString()}</span><span><button className="inline-action" disabled={!canOperate || !!busy || !stopped} title={!stopped ? "Stop the server before restoring" : undefined} onClick={() => void queue(backup.instance_id, "restore", backup.id)}>Restore</button></span></div>; }) : <div className="table-empty">No backups yet. Create one from a managed server.</div>}</div></div>;
}
function Jobs() { const [jobs,setJobs]=useState<Job[]>([]); const [filter,setFilter]=useState("all"); const [error,setError]=useState(""); useEffect(()=>{let stopped=false; const load=()=>api<{items:Job[]}>("/jobs?limit=50").then(r=>{if(!stopped){setJobs(r.items);setError("")}}).catch(e=>{if(!stopped)setError(e.message)}); void load(); const timer=window.setInterval(()=>void load(),5000); return()=>{stopped=true;window.clearInterval(timer)}},[]); const visible=filter === "all" ? jobs : jobs.filter(job=>job.status === filter); return <div className="page-stack">{error && <div className="alert error" role="alert">Could not refresh jobs: {error}</div>}<section className="section-heading"><div><p className="eyebrow">EXECUTION QUEUE</p><h2>Jobs</h2></div><div className="jobs-tools"><select className="job-filter" aria-label="Filter jobs by status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="queued">Queued</option><option value="leased">Leased</option><option value="running">Running</option><option value="succeeded">Succeeded</option><option value="failed">Failed</option></select><span className="subtle">{visible.length} shown · auto-refresh 5s</span></div></section><JobTable jobs={visible} detailed /></div> }
function JobTable({ jobs, detailed = false }: { jobs: Job[]; detailed?: boolean }) { return <div className="table-card card"><div className="table-head"><span>JOB</span><span>TYPE</span><span>STATUS</span><span>CREATED</span></div>{jobs.length ? jobs.map(job=><div className="table-row" key={job.id}><span className="mono">{job.id.slice(0,10)}…</span><span>{job.kind}</span><span><b className={`job-status ${job.status}`}>{job.status}</b>{detailed && job.last_error && <small className="row-error">{job.last_error}</small>}</span><span className="subtle">{new Date(job.created_at).toLocaleString()}</span></div>) : <div className="table-empty">No jobs yet. Actions will appear here.</div>}</div> }
function AuditList({ items }: { items: Audit[] }) { return <div className="audit-list card">{items.length ? items.map(item=><div className="audit-row" key={item.id}><div className="audit-dot" /><div><strong>{item.action}</strong><p>{item.actor} · {item.resource}</p></div><time>{new Date(item.created_at).toLocaleString()}</time></div>) : <div className="table-empty">No activity recorded yet.</div>}</div> }
function Audit() { const [items,setItems]=useState<Audit[]>([]); const [query,setQuery]=useState(""); const [error,setError]=useState(""); useEffect(()=>{let stopped=false; const load=()=>api<{items:Audit[]}>("/audit?limit=50").then(r=>{if(!stopped){setItems(r.items);setError("")}}).catch(e=>{if(!stopped)setError(e.message)}); void load(); const timer=window.setInterval(()=>void load(),5000); return()=>{stopped=true;window.clearInterval(timer)}},[]); const normalized=query.trim().toLowerCase(); const visible=normalized ? items.filter(item=>`${item.action} ${item.actor} ${item.resource}`.toLowerCase().includes(normalized)) : items; return <div className="page-stack">{error && <div className="alert error" role="alert">Could not refresh audit trail: {error}</div>}<section className="section-heading"><div><p className="eyebrow">ACCOUNTABILITY</p><h2>Audit trail</h2></div><div className="audit-tools"><input className="audit-search" aria-label="Search audit trail" placeholder="Search activity" value={query} onChange={e=>setQuery(e.target.value)} /><span className="subtle">{visible.length} shown · auto-refresh 5s</span></div></section><AuditList items={visible} /></div> }
function nodeStatusClass(status: string) { return status === "online" ? "succeeded" : status === "degraded" ? "queued" : status === "offline" ? "failed" : ""; }
function Nodes() {
  const [items, setItems] = useState<Node[]>([]); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [endpoint, setEndpoint] = useState(""); const [error, setError] = useState(""); const [enrollmentNodeID, setEnrollmentNodeID] = useState(""); const [enrollmentToken, setEnrollmentToken] = useState(""); const [enrollmentExpiry, setEnrollmentExpiry] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => api<{ items: Node[] }>("/nodes?limit=50").then(r => { setItems(r.items); setError(""); }).catch(e => setError(e.message));
  useEffect(() => { let stopped = false; const refresh = () => { if (!stopped) void load(); }; refresh(); const timer = window.setInterval(refresh, 5000); return () => { stopped = true; window.clearInterval(timer); }; }, []);
  async function create(event: FormEvent) { event.preventDefault(); setError(""); setEnrollmentToken(""); setBusy(true); try { const result = await api<{ id: string; enrollment_token: string; enrollment_expires_at: string }>("/nodes", { method: "POST", headers: { "X-CSRF-Token": await csrfToken() }, body: JSON.stringify({ name, endpoint }) }); setEnrollmentNodeID(result.id); setEnrollmentToken(result.enrollment_token); setEnrollmentExpiry(result.enrollment_expires_at); setName(""); setEndpoint(""); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not create node"); } finally { setBusy(false); } }
  return <div className="page-stack">{enrollmentToken && <div className="alert success enrollment-alert" role="status"><strong>Node registered: {enrollmentNodeID}</strong><span>Use this exact node ID with the one-use token. It expires {new Date(enrollmentExpiry).toLocaleString()}.</span><code>{enrollmentToken}</code></div>}<section className="section-heading"><div><p className="eyebrow">CLUSTER TOPOLOGY</p><h2>Nodes</h2><p className="subtle">Register an agent, then exchange its one-use token for a client certificate.</p></div><div className="heading-actions"><span className="subtle">Auto-refresh 5s</span><button className="primary" onClick={() => setOpen(!open)}>+ Register node</button></div></section>{open && <form className="card invite-card" onSubmit={create}><p className="eyebrow">NEW AGENT NODE</p><div className="form-row"><input aria-label="Node name" value={name} onChange={e => setName(e.target.value)} placeholder="Node name" required /><input aria-label="Node endpoint" type="url" value={endpoint} onChange={e => setEndpoint(e.target.value)} placeholder="https://node.example" required /><button className="primary" disabled={busy}>{busy ? "Registering…" : "Register"}</button></div>{error && <div className="alert error" role="alert">{error}</div>}</form>}{error && !open && <div className="alert error" role="alert">{error}</div>}<div className="table-card card"><div className="table-head"><span>NODE</span><span>ENDPOINT</span><span>STATUS</span><span>HEARTBEAT</span></div>{items.length ? items.map(item => <div className="table-row" key={item.id}><span><b className="user-avatar">⌁</b>{item.name}</span><span className="mono">{item.endpoint}</span><span><b className={`job-status ${nodeStatusClass(item.status)}`}>{item.status}</b></span><span className="subtle">{item.last_heartbeat ? new Date(item.last_heartbeat).toLocaleString() : "Never"}</span></div>) : <div className="table-empty">No nodes registered yet.</div>}</div></div>
}
function Users({ currentUser }: { currentUser: User }) {
  const [items, setItems] = useState<User[]>([]); const [open, setOpen] = useState(false); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<User["role"]>("viewer"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => api<{ items: User[] }>("/users").then(r => { setItems(r.items); setError(""); }).catch(e => setError(e.message));
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setError(""); setNotice(""); setBusy(true); try { await api("/users", { method: "POST", headers: { "X-CSRF-Token": await csrfToken() }, body: JSON.stringify({ username, password, role }) }); setUsername(""); setPassword(""); setOpen(false); setNotice(`${username} was added as ${role}.`); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not create user"); } finally { setBusy(false); } }
  async function update(id: string, changes: { role?: User["role"], disabled?: boolean }) { if (changes.disabled === true && !window.confirm("Disable this account? The user will be signed out and unable to access the console.")) return; setError(""); setNotice(""); try { await api(`/users/${id}`, { method: "PATCH", headers: { "X-CSRF-Token": await csrfToken() }, body: JSON.stringify(changes) }); setNotice("User account updated."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not update user"); } }
  return <div className="page-stack"><section className="section-heading"><div><p className="eyebrow">ACCESS CONTROL</p><h2>Team access</h2><p className="subtle">Role changes for your own account require another administrator.</p></div><button className="primary" onClick={() => { setNotice(""); setOpen(!open); }}>+ Invite user</button></section>{notice && <div className="alert success" role="status">{notice}</div>}{open && <form className="card invite-card" onSubmit={create}><p className="eyebrow">NEW OPERATOR</p><div className="form-row"><input aria-label="New username" value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" required /><select aria-label="New role" value={role} onChange={e => setRole(e.target.value as User["role"])}><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Admin</option></select><input aria-label="Temporary password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="12+ character password" minLength={12} required /><button className="primary" disabled={busy}>{busy ? "Creating…" : "Create"}</button></div>{error && <div className="alert error" role="alert">{error}</div>}</form>}{error && !open && <div className="alert error" role="alert">{error}</div>}<div className="table-card card"><div className="table-head"><span>USER</span><span>ROLE</span><span>STATUS</span><span>ADDED</span></div>{items.map(item=><div className="table-row" key={item.id}><span><b className="user-avatar">{item.username[0].toUpperCase()}</b>{item.username}{item.id === currentUser.id && <small className="current-user">you</small>}</span><select className="role-select" aria-label={`Role for ${item.username}`} value={item.role} disabled={item.id === currentUser.id} title={item.id === currentUser.id ? "Ask another administrator to change your role" : undefined} onChange={e => void update(item.id, { role: e.target.value as User["role"] })}><option value="viewer">viewer</option><option value="operator">operator</option><option value="admin">admin</option></select><span><b className={`job-status ${item.disabled_at ? "failed" : "succeeded"}`}>{item.disabled_at ? "disabled" : "active"}</b>{item.id !== currentUser.id && <button className="inline-action" onClick={() => void update(item.id, { disabled: !item.disabled_at })}>{item.disabled_at ? "Enable" : "Disable"}</button>}</span><span className="subtle">{item.created_at ? new Date(item.created_at).toLocaleDateString() : "—"}</span></div>)}</div></div>
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
