import React, { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type User = { id: string; username: string; role: "admin" | "operator" | "viewer" };
type Instance = { id: string; node_id?: string; cluster_id?: string; map_name: string; desired_state: string; observed_state: string; health: string; last_error?: string | null };
type Job = { id: string; instance_id?: string | null; kind: string; status: string; last_error?: string | null; created_at: string };
type Audit = { id: number; actor: string; action: string; resource: string; metadata: Record<string, unknown>; created_at: string };

const api = async <T,>(path: string, init?: RequestInit): Promise<T> => {
  const response = await fetch(`/api/v1${path}`, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(init?.headers || {}) }, ...init });
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body?.error?.message || "Request failed"); }
  return response.json();
};

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { const result = await api<{ user: User }>("/auth/login", { method: "POST", body: JSON.stringify({ username, password }) }); onLogin(result.user); } catch (e) { setError(e instanceof Error ? e.message : "Unable to sign in"); } finally { setBusy(false); } }
  return <main className="login-layout"><section className="login-visual"><div className="brand-mark">A<span>•</span></div><p className="eyebrow">ARK ASA / OPERATIONS</p><h1>Keep your<br /><em>world online.</em></h1><p className="login-copy">A calm command surface for servers, jobs, and the people who keep your cluster moving.</p><div className="orbit"><span /><span /><span /></div></section><section className="login-panel"><div className="login-card"><p className="eyebrow">SECURE ACCESS</p><h2>Welcome back</h2><p className="muted">Sign in to your operations console.</p><form onSubmit={submit}><label>Username<input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} placeholder="admin" required /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••••••" required /></label>{error && <div className="alert error" role="alert">{error}</div>}<button className="primary wide" disabled={busy}>{busy ? "Signing in…" : "Enter console"}<span>↗</span></button></form><p className="security-note">Sessions are protected with secure, same-origin cookies.</p></div></section></main>;
}

function App() {
  const [user, setUser] = useState<User | null>(null); const [checking, setChecking] = useState(true); const [page, setPage] = useState("overview"); const [nodeHealth, setNodeHealth] = useState("unknown");
  useEffect(() => {
    api<{ authenticated: boolean; user?: User }>("/auth/status").then(r => setUser(r.authenticated ? r.user || null : null)).catch(() => setUser(null)).finally(() => setChecking(false));
  }, []);
  useEffect(() => { if (user) void api<any>("/system/health").then(r => setNodeHealth(r.agent || "unknown")).catch(() => setNodeHealth("unknown")); }, [user]);
  if (checking) return <div className="loading-screen"><div className="spinner" />Loading console</div>;
  if (!user) return <Login onLogin={setUser} />;
  async function logout() { await api("/auth/logout", { method: "POST", headers: { "X-CSRF-Token": getCookie("ark_csrf") || "" } }).catch(() => undefined); setUser(null); }
  return <div className="app-shell"><Sidebar page={page} setPage={setPage} user={user} logout={logout} nodeHealth={nodeHealth} /><main className="content"><header className="topbar"><div><p className="eyebrow">CONTROL PLANE / LOCAL</p><h1>{page === "overview" ? "Good evening, " + user.username : pageLabel(page)}</h1></div><div className="top-actions"><span className="live-pill"><i /> Live</span><div className="avatar">{user.username.slice(0, 1).toUpperCase()}</div></div></header>{page === "overview" && <Overview user={user} />}{page === "servers" && <Servers user={user} />}{page === "jobs" && <Jobs />}{page === "audit" && <Audit />}{page === "users" && user.role === "admin" && <Users />}</main></div>;
}

function Sidebar({ page, setPage, user, logout, nodeHealth }: { page: string; setPage: (p: string) => void; user: User; logout: () => void; nodeHealth: string }) { const links = [{ id: "overview", label: "Overview", icon: "⌂" }, { id: "servers", label: "Servers", icon: "◈" }, { id: "jobs", label: "Jobs", icon: "◌" }, { id: "audit", label: "Audit trail", icon: "≡" }]; const label = nodeHealth === "healthy" ? "healthy" : nodeHealth === "degraded" ? "degraded" : "checking"; return <aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark small">A<span>•</span></div><span>ARK / OPS</span></div><nav>{links.map(link => <button className={page === link.id ? "nav-link active" : "nav-link"} key={link.id} onClick={() => setPage(link.id)}><b>{link.icon}</b>{link.label}</button>)}{user.role === "admin" && <button className={page === "users" ? "nav-link active" : "nav-link"} onClick={() => setPage("users")}><b>♙</b>Team access</button>}</nav><div className="sidebar-bottom"><div className="node-status"><i />Local node <span>{label}</span></div><button className="logout" onClick={logout}>↪ <span>Sign out</span></button></div></aside> }
function pageLabel(page: string) { return ({ servers: "Servers", jobs: "Jobs", audit: "Audit trail", users: "Team access" } as Record<string, string>)[page] || "Overview"; }
function getCookie(name: string) { return document.cookie.split("; ").find(v => v.startsWith(`${name}=`))?.slice(name.length + 1) || ""; }
function Metric({ label, value, detail, tone = "green" }: { label: string; value: string; detail: string; tone?: string }) { return <article className="metric card"><div className={`metric-icon ${tone}`}>{tone === "green" ? "✓" : tone === "amber" ? "◌" : "⌁"}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article> }

function Overview({ user }: { user: User }) {
  const [health, setHealth] = useState<any>(null); const [instances, setInstances] = useState<Instance[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [error, setError] = useState("");
  useEffect(() => {
    const load = () => Promise.all([api<any>("/system/health"), api<{ items: Instance[] }>("/instances"), api<{ items: Job[] }>("/jobs?limit=5")]).then(([h, i, j]) => { setHealth(h); setInstances(i.items); setJobs(j.items); }).catch(e => setError(e.message));
    void load();
    const scheme = window.location.protocol === "https:" ? "wss" : "ws"; let cursor = 0; let stopped = false; let retry: number | undefined; let socket: WebSocket;
    const connect = () => { if (stopped) return; socket = new WebSocket(`${scheme}://${window.location.host}/api/v1/ws?cursor=${cursor}`); socket.onmessage = event => { const message = JSON.parse(event.data); if (message?.type === "event") { cursor = Number(message.cursor) || cursor; void load(); } }; socket.onclose = () => { if (!stopped) retry = window.setTimeout(connect, 2000); }; };
    connect();
    return () => { stopped = true; if (retry) window.clearTimeout(retry); socket?.close(); };
  }, []);
  const instance = instances[0]; const agentValue = health?.agent === "healthy" ? "Ready" : health?.agent === "degraded" ? "Degraded" : "Checking"; return <div className="page-stack">{error && <div className="alert error">{error}</div>}<section className="hero-grid"><div className="hero-card card"><div><p className="eyebrow amber">OPERATIONS AT A GLANCE</p><h2>Your servers,<br /><em>in good hands.</em></h2><p>Monitor health, trigger safe actions, and keep a clean record of every change.</p></div><div className="hero-ring"><span>{instances.length}</span><small>instances</small></div></div><div className="metric-grid"><Metric label="Control plane" value={health?.control_plane === "healthy" ? "Healthy" : "Checking"} detail="Database connected" /><Metric label="Agent node" value={agentValue} detail={health?.agent === "healthy" ? "Last heartbeat · live" : "Heartbeat unavailable"} tone="blue" /></div></section><section className="section-heading"><div><p className="eyebrow">YOUR INFRASTRUCTURE</p><h2>Server overview</h2></div><span className="subtle">{instances.length} instance{instances.length === 1 ? "" : "s"}</span></section>{instance ? <ServerCard instance={instance} user={user} /> : <div className="empty card"><div className="empty-icon">◈</div><h3>No server registered yet</h3><p>Once an instance is connected to the local node, it will appear here.</p></div>}<section className="section-heading compact"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Latest jobs</h2></div><span className="subtle">Last 5</span></section><JobTable jobs={jobs} /></div>
}

function ServerCard({ instance, user }: { instance: Instance; user?: User }) { const [busy, setBusy] = useState(""); const [feedback, setFeedback] = useState(""); const canOperate = user?.role !== "viewer"; async function action(name: string) { if (!canOperate) return; if ((name === "stop" || name === "restart") && !window.confirm(`Confirm ${name} for ${instance.id}?`)) return; setFeedback(""); setBusy(name); try { await api(`/instances/${instance.id}/actions/${name}`, { method: "POST", headers: { "X-CSRF-Token": getCookie("ark_csrf") || "" } }); setFeedback(`${name[0].toUpperCase() + name.slice(1)} queued. Track progress in Jobs.`); } catch (e) { setFeedback(e instanceof Error ? e.message : "Could not queue action"); } finally { setBusy(""); } } return <article className="server-card card"><div className="server-title"><div className="server-icon">✦</div><div><h3>{instance.id}</h3><p>{instance.map_name} · desired {instance.desired_state}</p></div><span className={`status ${instance.health === "healthy" ? "ok" : "warn"}`}><i />{instance.health}</span></div><div className="server-meta"><div><span>OBSERVED STATE</span><strong>{instance.observed_state}</strong></div><div><span>CLUSTER</span><strong>{instance.cluster_id || "—"}</strong></div><div><span>NODE</span><strong>{instance.node_id || "—"}</strong></div></div><div className="server-actions"><button onClick={() => action("start")} disabled={!!busy || !canOperate} title={!canOperate ? "Viewer access is read-only" : undefined}>Start</button><button onClick={() => action("restart")} disabled={!!busy || !canOperate} title={!canOperate ? "Viewer access is read-only" : undefined}>Restart</button><button className="danger" onClick={() => action("stop")} disabled={!!busy || !canOperate} title={!canOperate ? "Viewer access is read-only" : undefined}>{busy || "Stop"}</button></div>{feedback && <div className={`action-feedback ${feedback.startsWith("Could") ? "error" : "success"}`} role="status" aria-live="polite">{feedback}</div>}</article> }
function Servers({ user }: { user: User }) { const [items,setItems]=useState<Instance[]>([]); const [error,setError]=useState(""); const load=()=>api<{items:Instance[]}>("/instances").then(r=>setItems(r.items)).catch(e=>setError(e.message)); useEffect(()=>{void load()},[]); return <div className="page-stack">{error && <div className="alert error" role="alert">{error}</div>}<section className="section-heading"><div><p className="eyebrow">INFRASTRUCTURE</p><h2>Servers</h2></div><span className="subtle">{user.role} access</span></section>{items.length ? items.map(i=><ServerCard key={i.id} instance={i} user={user}/>) : <div className="empty card"><div className="empty-icon">◈</div><h3>No servers found</h3><p>Register an instance with the control plane to start managing it.</p></div>}</div> }
function Jobs() { const [jobs,setJobs]=useState<Job[]>([]); useEffect(()=>{api<{items:Job[]}>("/jobs?limit=50").then(r=>setJobs(r.items)).catch(()=>undefined)},[]); return <div className="page-stack"><section className="section-heading"><div><p className="eyebrow">EXECUTION QUEUE</p><h2>Jobs</h2></div><span className="subtle">{jobs.length} recent</span></section><JobTable jobs={jobs} detailed /></div> }
function JobTable({ jobs, detailed = false }: { jobs: Job[]; detailed?: boolean }) { return <div className="table-card card"><div className="table-head"><span>JOB</span><span>TYPE</span><span>STATUS</span><span>CREATED</span></div>{jobs.length ? jobs.map(job=><div className="table-row" key={job.id}><span className="mono">{job.id.slice(0,10)}…</span><span>{job.kind}</span><span><b className={`job-status ${job.status}`}>{job.status}</b>{detailed && job.last_error && <small className="row-error">{job.last_error}</small>}</span><span className="subtle">{new Date(job.created_at).toLocaleString()}</span></div>) : <div className="table-empty">No jobs yet. Actions will appear here.</div>}</div> }
function Audit() { const [items,setItems]=useState<Audit[]>([]); useEffect(()=>{api<{items:Audit[]}>("/audit?limit=50").then(r=>setItems(r.items)).catch(()=>undefined)},[]); return <div className="page-stack"><section className="section-heading"><div><p className="eyebrow">ACCOUNTABILITY</p><h2>Audit trail</h2></div><span className="subtle">Immutable activity log</span></section><div className="audit-list card">{items.length ? items.map(item=><div className="audit-row" key={item.id}><div className="audit-dot" /><div><strong>{item.action}</strong><p>{item.actor} · {item.resource}</p></div><time>{new Date(item.created_at).toLocaleString()}</time></div>) : <div className="table-empty">No activity recorded yet.</div>}</div></div> }
function Users() {
  const [items, setItems] = useState<User[]>([]); const [open, setOpen] = useState(false); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<User["role"]>("viewer"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => api<{ items: User[] }>("/users").then(r => setItems(r.items)).catch(e => setError(e.message));
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { await api("/users", { method: "POST", headers: { "X-CSRF-Token": getCookie("ark_csrf") || "" }, body: JSON.stringify({ username, password, role }) }); setUsername(""); setPassword(""); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not create user"); } finally { setBusy(false); } }
  return <div className="page-stack"><section className="section-heading"><div><p className="eyebrow">ACCESS CONTROL</p><h2>Team access</h2></div><button className="primary" onClick={() => setOpen(!open)}>+ Invite user</button></section>{open && <form className="card invite-card" onSubmit={create}><p className="eyebrow">NEW OPERATOR</p><div className="form-row"><input aria-label="New username" value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" required /><select aria-label="New role" value={role} onChange={e => setRole(e.target.value as User["role"])}><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Admin</option></select><input aria-label="Temporary password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="12+ character password" minLength={12} required /><button className="primary" disabled={busy}>{busy ? "Creating…" : "Create"}</button></div>{error && <div className="alert error">{error}</div>}</form>}{error && !open && <div className="alert error">{error}</div>}<div className="table-card card"><div className="table-head"><span>USER</span><span>ROLE</span><span>STATUS</span><span>ADDED</span></div>{items.map(item=><div className="table-row" key={item.id}><span><b className="user-avatar">{item.username[0].toUpperCase()}</b>{item.username}</span><span className="role-chip">{item.role}</span><span className="job-status succeeded">active</span><span className="subtle">—</span></div>)}</div></div>
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
